# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDOSStencilExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDOSStencil
  pod 'SDOSStencil', :path => '../../'
  

  #Realm
  pod 'RealmSwift', '4.3.0'

end
